# Permalinks
#
permalink:           /:categories/:year/:month/:day/:title/

# Setup
title:               'Samuel Steven Smith'
tagline:             Personal Webiste
description:         An early career neuroscientist investigating the auditory brain.
url:                 http://samstesmi.github.io
baseurl:             /
paginate:            3

# Plugins, Tags, Categories and Analytics
plugins:          [jekyll-paginate]

# About/contact
author:
  name:              Samuel Smith
  url:               http://samstesmi.github.io
  email:             samuel.smith@nottingham.ac.uk
